### ISSUE TITLE
Fix display of games etc.

### ISSUE THREAD

**Issue by cpkm** [cpkm/darts-site#11]
Change format for lists of games etc. to be more simply laid out ad visually appealing.

**Comment by r3dunlop** [comment]
This could include the breaking apart of different seasons. Right now everything falls under "Current Season" in the "Enter Scores" tab.

**Comment by cpkm** [comment]
Ya and it's the basically in all places they are listed (when not using the HTML template)

**Comment by cpkm** [comment]
closed in #107
