### ISSUE TITLE
Captain view who is checked in

### ISSUE THREAD

**Issue by cpkm** [cpkm/darts-site#114]
In the captain portal, show who is checked in for each game (not just the number)

**Comment by r3dunlop** [comment]
Can we take the captain view off or integrate this into the match view? It might be worth it for everyone can see who has checked in or out. The captain view could allow the captain to manipulate the current status of players.

**Comment by r3dunlop** [comment]
Cool. The way I've been coding it makes it column number and order agnostic. All that matters is that you have the columns named correctly. This was mostly looking forward to potentially scraping the pdf or website and not wanting to think about things like debugging the shape of the table.

**Comment by cpkm** [comment]
perfect

**Comment by cpkm** [comment]
ya we should add it to the match or schedule (which needs a revamp anyway). But I'll make that a new issue.
