### ISSUE TITLE
CSV import of schedule

### ISSUE THREAD

**Issue by cpkm** [cpkm/darts-site#12]
create a bulk import option for schedules. Allow for csv file of date, opponent, home/away, playoff and automatically generate the match database entries.

**Comment by r3dunlop** [comment]
What should be the UI goal here? Will one upload a csv? or will they copy text into a text-field? My plan is to generate the back end functionality in a module and let someone else (could be me again) integrate it into the front end.

**Comment by cpkm** [comment]
I'd say upload a csv with a set column format.

**Comment by r3dunlop** [comment]
Cool. The way I've been coding it makes it column number and order agnostic. All that matters is that you have the columns named correctly. This was mostly looking forward to potentially scraping the pdf or website and not wanting to think about things like debugging the shape of the table.

**Comment by r3dunlop** [comment]
Regular season import is complete in #126
