### ISSUE TITLE
Sub designation

### ISSUE THREAD

**Issue by r3dunlop** [cpkm/darts-site#145]
Make a sub designation for players we invite as subs. This may have several uses (inputting scores etc). May be extendable in the future...setting windows for when someone is a sub etc.

**Comment by cpkm** [comment]
This may serve as a replacement for the is_active flag in the player model. For example, have captain, assistant, and player as 'active' roles, sub as 'inactive' but is displayed in entry forms, and add a retired role (or something) for players we don't need anywhere.

We can add a .is_active() method to the Player model, which would check the role as I said above and return True/False. We can also expand the method current_roster() to allow inputs for various roster configurations, e.g. active players, active plus subs, full, etc. to serve as a catch-all way to deliver player lists.

**Comment by cpkm** [comment]
closed in #158
