### ISSUE TITLE
Safari display issues

### ISSUE THREAD

**Issue by cpkm** [cpkm/darts-site#152]
When using Safari browser, all grid items collapse vertically, regardless of screen size. This is a bootstrap/Safari bug

**Comment by r3dunlop** [comment]
Sounds more to me like "ICC 4 does not support safari browser" :-p.

**Comment by cpkm** [comment]
No everything is there and fine, it just always looks like you're on mobile lol. Everything is stacked vertically.

**Comment by cpkm** [comment]
closed in 28108336fdd850e3ef1c9706f7351ea0cf7cab9b

needed to add a css line for .row before and after elements
