### ISSUE TITLE
Allow users to check in, out, or if needed 

### ISSUE THREAD

**Issue by r3dunlop** [cpkm/darts-site#59]
As a captain, I want to know if a user is coming or not. They can also check 'if needed' so that I know to ask them to come if we are under 8 people.

**Comment by r3dunlop** [comment]
- I think this will need an association table that uses match_id, user_id, in/out/maybe. 
- Implementation could be to show a set of buttons on the match form that are active until game time.

**Comment by cpkm** [comment]
closed in #100
