### ISSUE TITLE
Input 2018-2019 game-by-game data

### ISSUE THREAD

**Issue by r3dunlop** [cpkm/darts-site#66]

**Comment by cpkm** [comment]
2018-2019 is last season, which I think is completely input. Do you mean 2017-2018?

**Comment by r3dunlop** [comment]
Last season was completely input? There are 20 games recorded. We played 14 regular season (15 teams) + 8 playoffs (2 * 4 game from 5 teams in our division). So I believe that we are missing 2 games somewhere. I'll close this once we figure out the answer to that question.

**Comment by cpkm** [comment]
They will likely just be the last two game of the playoffs then. Will you check the book when you get home?

**Comment by r3dunlop** [comment]
I'll try to remember. I'll send you the pictures of the games because I don't have privileges to add games as it is.
