### ISSUE TITLE
Send automated email reminders for games

### ISSUE THREAD

**Issue by cpkm** [cpkm/darts-site#80]
Game reminders should be sent out, e.g. 5 days before and day before a game. This email would also contain the check in/out links #59 #60

**Comment by cpkm** [comment]
Scheduling emails seems to be relatively straight forward, but requires a decent amount of work.

My basic approach will be:
- create an association table for UserGameReminders.
- each entry would correspond to a single email reminder event, e.g. UserA for GameB X days in advance.
- each entry would possess a datetime to be sent.
- a scheduled task (e.g once a day) would then query the table for unsent reminders which are to be sent in a given time window.
- from the list of reminders emails can be constructed and sent.
- table entries should then be deleted after the email is sent.

Notes:
- table entries must be created when a Game is added.
- is a player is checked-out of a given game, no email should be sent.
- only players on the active roster should receive emails.

**Comment by r3dunlop** [comment]
We should break this down into a bunch of smaller issues. Also, for this milestone, I'd be happy just putting a button that can be clicked to send the emails. The cron job stuff can be set up later, and the button will maintain it's usefulness.

**Comment by cpkm** [comment]
Ya that sounds good. I'll specify this issue to automated reminders.

**Comment by cpkm** [comment]
For now I am going to simply use Heroku Scheduler. This will make implementation easy, at the expense of customizability. Users, i.e. captains will not be able to modify the time of emails.

Scheduled tasks should be written as scripts in the tasks folder.

**Comment by cpkm** [comment]
closed in #153
